### ISSUE TITLE
TLS Websocket server fails with go 1.9

### ISSUE THREAD

**Issue by ronanj** [gammazero/nexus#140]
I am running the following setup:

Server: `go run server/server.go`

```
2018/07/30 10:31:30 Starting router
2018/07/30 10:31:30 Added realm: nexus.examples
2018/07/30 10:31:30 Websocket server listening on ws://127.0.0.1:8000/
2018/07/30 10:31:30 RawSocket TCP server listening on tcp://127.0.0.1:8001/
2018/07/30 10:31:30 RawSocket unix server listening on unix:///tmp/exmpl_nexus_sock
2018/07/30 10:31:30 TLS Websocket server listening on wss://127.0.0.1:8100/
2018/07/30 10:31:30 TLS RawSocket TCP server listening on tcps://127.0.0.1:8101/
```

Client: `go run pubsub/subscriber/subscriber.go -scheme=wss -trust=server/cert.pem`

Then, the server fails with 

```
2018/07/30 10:31:34 http: panic serving 127.0.0.1:60838: interface conversion: net.Conn is *tls.Conn, not *net.TCPConn
goroutine 30 [running]:
net/http.(*conn).serve.func1(0xc4201e0280)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1726 +0xd0
panic(0x15325c0, 0xc4201ba180)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/gammazero/nexus/router.(*WebsocketServer).ServeHTTP(0xc42018a2a0, 0x16630c0, 0xc4201a2380, 0xc4201ae200)
```

**Comment by ronanj** [comment]
If switching to the `go server.ServeTLS(l, certFile, keyFile)` in `websocketserver.go`, it still fails, but with a different error:

```
2018/07/30 10:43:33 http: TLS handshake error from 127.0.0.1:61124: tls: first record does not look like a TLS handshake
```

**Comment by gammazero** [comment]
I think you are seeing #135, which is fixed.   Please get update.  I am not seeing this problem:
```
> go run pubsub/subscriber/subscriber.go -scheme=wss -trust=server/cert.pem
2018/07/30 16:37:06 Trusting certificate server/cert.pem with CN: Andrew Gillis
SUBSCRIBER> Connected to wss://localhost:8100/ using json serialization
SUBSCRIBER> Subscribed to example.hello
```

**Comment by ronanjs** [comment]
Upgrading to the latest release fixed this issue. Thanks
