### ISSUE TITLE
Using wamp.session.list segfaults the router

### ISSUE THREAD

**Issue by johannwagner** [gammazero/nexus#175]
Hey,

I just tried to use `wamp.session.list` with an auth role filter, as described [here](https://wamp-proto.org/_static/gen/wamp_latest.html#wamp-session-list).

My call using kraftfahrstrasse: 

```
const [sessionListPromise] = socketConnection.Call('wamp.session.list', [['user']]);
```

Router Log:

```
interconnect_1           | panic: interface conversion: interface {} is []interface {}, not []string
interconnect_1           | 
interconnect_1           | goroutine 8 [running]:
interconnect_1           | github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router.(*realm).sessionList(0xc4201989c0, 0xc420179a00, 0x196520c5, 0x8a7d5c35da7c3d88)
interconnect_1           | 	/go/src/github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router/realm.go:829 +0x363
interconnect_1           | github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router.(*realm).(github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router.sessionList)-fm(0xc420179a00, 0xc420021350, 0x2)
interconnect_1           | 	/go/src/github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router/realm.go:267 +0x34
interconnect_1           | github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router.(*realm).metaProcedureHandler(0xc4201989c0)
interconnect_1           | 	/go/src/github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router/realm.go:774 +0x346
interconnect_1           | created by github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router.(*realm).run
interconnect_1           | 	/go/src/github.com/EmbeddedEnterprises/autobahnkreuz/vendor/github.com/gammazero/nexus/router/realm.go:298 +0x6cb
slimerp-service-deploy_interconnect_1 exited with code 2

```

https://github.com/gammazero/nexus/blob/master/router/realm.go#L829

I tried to figure out the issue in the code, but I was not able to and I think, I use this correctly. No matter what, this should not crash the entire router, even if this is not used correctly.

Best Regards, 
  Johann

**Comment by johannwagner** [comment]
@martin31821 has figured out the bug. Working on PR.
